<?php

namespace vnusWilliams\LarapexCharts\Console;

use vnusWilliams\LarapexCharts\Traits\WithModelStub;
use Illuminate\Console\GeneratorCommand;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;

class ChartMakeCommand extends GeneratorCommand
{
    use WithModelStub;

    protected array $chartTypes = [
        'Pie Chart'            => 'PieChart',
        'Donut Chart'          => 'DonutChart',
        'Radial Bar Chart'     => 'RadialBarChart',
        'Polar Area Chart'     => 'PolarAreaChart',
        'Line Chart'           => 'LineChart',
        'Area Chart'           => 'AreaChart',
        'Bar Chart'            => 'BarChart',
        'Horizontal Bar Chart' => 'HorizontalBarChart',
        'Heatmap Chart'        => 'HeatMapChart',
        'Radar Chart'          => 'RadarChart',
    ];

    protected ?string $selectedChart = null;

    protected function askChartType(): void
    {
        $option = $this->choice(
            'Select a chart type',
            array_keys($this->chartTypes),
        );
        $this->selectedChart = $this->chartTypes[$option];
    }

    public function handle(): ?bool
    {
        // --all option: generate a single class with all chart builders
        if ($this->option('all')) {
            return $this->handleAllCharts();
        }

        $this->askChartType();
        return parent::handle();
    }

    /**
     * Generate a single class containing builder methods for every chart type.
     * The user can delete the methods they don't need.
     */
    protected function handleAllCharts(): ?bool
    {
        $name      = $this->getNameInput();
        $namespace = $this->getDefaultNamespace($this->rootNamespace());
        $className = class_basename(str_replace('\\', '/', $this->qualifyClass($name)));

        $stub = $this->buildAllChartsStub($namespace, $className);

        $path = $this->getPath($this->qualifyClass($name));

        $this->makeDirectory($path);

        if ($this->files->exists($path) && ! $this->option('force')) {
            $this->components->error("{$this->type} already exists.");
            return false;
        }

        $this->files->put($path, $stub);

        $this->components->info(
            sprintf('%s [%s] created successfully.', $this->type, $path)
        );
        $this->line('');
        $this->line('  <fg=yellow>Tip:</> Delete the chart builder methods you do not need.');
        $this->line('');

        return true;
    }

    /**
     * Build the "all charts" stub content programmatically so it stays in sync
     * with the individual stubs and never goes stale.
     */
    protected function buildAllChartsStub(string $namespace, string $className): string
    {
        $methods = [
            $this->makePieChartMethod(),
            $this->makeDonutChartMethod(),
            $this->makeRadialBarChartMethod(),
            $this->makePolarAreaChartMethod(),
            $this->makeLineChartMethod(),
            $this->makeAreaChartMethod(),
            $this->makeBarChartMethod(),
            $this->makeHorizontalBarChartMethod(),
            $this->makeHeatMapChartMethod(),
            $this->makeRadarChartMethod(),
        ];

        $body = implode("\n\n", $methods);

        return <<<PHP
<?php

namespace {$namespace};

use vnusWilliams\LarapexCharts\LarapexChart;

/**
 * Chart class generated by LarapexCharts.
 *
 * This class contains a builder method for every chart type.
 * Feel free to delete the methods you don't need and rename
 * each method to something meaningful for your application.
 */
class {$className}
{
{$body}
}
PHP;
    }

    // ─── Individual method builders ──────────────────────────────────────────

    protected function makePieChartMethod(): string
    {
        return <<<'METHOD'
    public function pieChart(): \vnusWilliams\LarapexCharts\PieChart
    {
        return (new LarapexChart)->pieChart()
            ->setTitle('Top 3 scorers of the team.')
            ->setSubtitle('Season 2021.')
            ->addData([40, 50, 30])
            ->setLabels(['Player 7', 'Player 10', 'Player 9']);
    }
METHOD;
    }

    protected function makeDonutChartMethod(): string
    {
        return <<<'METHOD'
    public function donutChart(): \vnusWilliams\LarapexCharts\DonutChart
    {
        return (new LarapexChart)->donutChart()
            ->setTitle('Top 3 scorers of the team.')
            ->setSubtitle('Season 2021.')
            ->addData([20, 24, 30])
            ->setLabels(['Player 7', 'Player 10', 'Player 9']);
    }
METHOD;
    }

    protected function makeRadialBarChartMethod(): string
    {
        return <<<'METHOD'
    public function radialBarChart(): \vnusWilliams\LarapexCharts\RadialChart
    {
        return (new LarapexChart)->radialChart()
            ->setTitle('Passing effectiveness.')
            ->setSubtitle('Barcelona city vs Madrid sports.')
            ->addData([75, 60])
            ->setLabels(['Barcelona city', 'Madrid sports'])
            ->setColors(['#D32F2F', '#03A9F4']);
    }
METHOD;
    }

    protected function makePolarAreaChartMethod(): string
    {
        return <<<'METHOD'
    public function polarAreaChart(): \vnusWilliams\LarapexCharts\PolarAreaChart
    {
        return (new LarapexChart)->polarAreaChart()
            ->setTitle('Top 3 scorers of the team.')
            ->setSubtitle('Season 2021.')
            ->addData([20, 24, 30])
            ->setLabels(['Player 7', 'Player 10', 'Player 9']);
    }
METHOD;
    }

    protected function makeLineChartMethod(): string
    {
        return <<<'METHOD'
    public function lineChart(): \vnusWilliams\LarapexCharts\LineChart
    {
        return (new LarapexChart)->lineChart()
            ->setTitle('Sales during 2021.')
            ->setSubtitle('Physical sales vs Digital sales.')
            ->addData([40, 93, 35, 42, 18, 82], 'Physical sales')
            ->addData([70, 29, 77, 28, 55, 45], 'Digital sales')
            ->setXAxis(['January', 'February', 'March', 'April', 'May', 'June']);
    }
METHOD;
    }

    protected function makeAreaChartMethod(): string
    {
        return <<<'METHOD'
    public function areaChart(): \vnusWilliams\LarapexCharts\AreaChart
    {
        return (new LarapexChart)->areaChart()
            ->setTitle('Sales during 2021.')
            ->setSubtitle('Physical sales vs Digital sales.')
            ->addData([40, 93, 35, 42, 18, 82], 'Physical sales')
            ->addData([70, 29, 77, 28, 55, 45], 'Digital sales')
            ->setXAxis(['January', 'February', 'March', 'April', 'May', 'June']);
    }
METHOD;
    }

    protected function makeBarChartMethod(): string
    {
        return <<<'METHOD'
    public function barChart(): \vnusWilliams\LarapexCharts\BarChart
    {
        return (new LarapexChart)->barChart()
            ->setTitle('San Francisco vs Boston.')
            ->setSubtitle('Wins during season 2021.')
            ->addData([6, 9, 3, 4, 10, 8], 'San Francisco')
            ->addData([7, 3, 8, 2, 6, 4], 'Boston')
            ->setXAxis(['January', 'February', 'March', 'April', 'May', 'June']);
    }
METHOD;
    }

    protected function makeHorizontalBarChartMethod(): string
    {
        return <<<'METHOD'
    public function horizontalBarChart(): \vnusWilliams\LarapexCharts\HorizontalBar
    {
        return (new LarapexChart)->horizontalBarChart()
            ->setTitle('Los Angeles vs Miami.')
            ->setSubtitle('Wins during season 2021.')
            ->setColors(['#FFC107', '#D32F2F'])
            ->addData([6, 9, 3, 4, 10, 8], 'Los Angeles')
            ->addData([7, 3, 8, 2, 6, 4], 'Miami')
            ->setXAxis(['January', 'February', 'March', 'April', 'May', 'June']);
    }
METHOD;
    }

    protected function makeHeatMapChartMethod(): string
    {
        return <<<'METHOD'
    public function heatMapChart(): \vnusWilliams\LarapexCharts\HeatMapChart
    {
        return (new LarapexChart)->heatMapChart()
            ->setTitle('Basic heatmap chart')
            ->addData([80, 50, 30, 40, 100, 20], 'Sales')
            ->addData([70, 10, 80, 20, 60, 40], 'Income')
            ->setMarkers(['#FFA41B', '#4F46E5'], 7, 10)
            ->setXAxis(['January', 'February', 'March', 'April', 'May', 'June']);
    }
METHOD;
    }

    protected function makeRadarChartMethod(): string
    {
        return <<<'METHOD'
    public function radarChart(): \vnusWilliams\LarapexCharts\RadarChart
    {
        return (new LarapexChart)->radarChart()
            ->setTitle('Individual Player Stats.')
            ->setSubtitle('Season 2021.')
            ->addData([70, 93, 78, 97, 50, 90], 'Stats')
            ->setXAxis(['Pass', 'Dribble', 'Shot', 'Stamina', 'Long shots', 'Tactical'])
            ->setMarkers(['#303F9F'], 7, 10);
    }
METHOD;
    }

    // ─── GeneratorCommand contract ────────────────────────────────────────────

    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'make:chart';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Creates a chart class';

    /**
     * The type of class being generated.
     *
     * @var string
     */
    protected $type = 'Chart class';

    /**
     * Get the stub file for the generator (used for single-type generation).
     */
    protected function getStub(): string
    {
        $directory = 'Default';

        if ($this->option('vue')) {
            $directory = 'Vue';
        }

        if ($this->option('json')) {
            $directory = 'Json';
        }

        $stub = "{$directory}/{$this->selectedChart}.stub";

        return $this->resolveStubPath($stub);
    }

    /**
     * Replace the class name for the given stub.
     */
    protected function replaceClass($stub, $name): string
    {
        $stub = parent::replaceClass($stub, $name);

        $className = class_basename(str_replace('\\', '/', $name));

        return str_replace('{{ name }}', $className, $stub);
    }

    /**
     * Get the default namespace for the class.
     */
    protected function getDefaultNamespace($rootNamespace): string
    {
        return $rootNamespace . '\Charts';
    }

    /**
     * Get the console command arguments.
     */
    protected function getArguments(): array
    {
        return [
            ['name', InputArgument::REQUIRED, 'The name of the chart class.'],
        ];
    }

    /**
     * Get the console command options.
     */
    protected function getOptions(): array
    {
        return [
            ['vue',   'vue',  InputOption::VALUE_NONE, 'Creates a chart class for a Vue component.'],
            ['json',  'json', InputOption::VALUE_NONE, 'Creates a chart class for a JSON API response.'],
            ['all',   null,   InputOption::VALUE_NONE, 'Generates a single class containing all chart types — delete what you do not need.'],
            ['force', null,   InputOption::VALUE_NONE, 'Overwrite the class if it already exists.'],
        ];
    }
}